# AUTOGENERATED! DO NOT EDIT! File to edit: download_recordings.ipynb (unless otherwise specified).

__all__ = ['download_recordings_by_bird', 'unzip_files']

# Cell
def download_recordings_by_bird(ebird_code):
    Path('dataset/'+ebird_code).mkdir(exist_ok=True)
    cmd = 'kaggle competitions download birdsong-recognition -p dataset/{} -f'.format(ebird_code)
    cmd = cmd.split(' ')

    specific_bird_files = train_files[train_files['ebird_code'] == ebird_code]['filename'].values

    print('number of files {}'.format(len(specific_bird_files)))

    for file in tqdm(range(len(specific_bird_files))):
        filename = 'train_audio/{}/{}'.format(ebird_code, specific_bird_files[file])
        new_cmd = cmd + [filename]
        subprocess.call(new_cmd)

# Cell
def unzip_files(ebird_id):
    ebird_folder = 'dataset/' + ebird_id
    files = glob.glob(ebird_folder+'/*')
    print('number of {} files: {}'.format(ebird_id, len(files)))

    zipped_files = [file for file in files if 'zip' in file]

    for file in zipped_files:
        subprocess.call(['unzip', file, '-d', ebird_folder])
        subprocess.call(['rm', file])

    files = glob.glob(ebird_folder+'/*')
    print('number of {} files after unzip:{}'.format(ebird_id, len(files)))